gcloud functions deploy ContentCompletion --region=us-west1 --trigger-event providers/cloud.pubsub/eventTypes/topic.publish --trigger-resource WeeklySync --runtime=nodejs16 --source=./ContentCompletion/ --entry-point sync --timeout=540s --set-env-vars=^}^client_id=3088ab0aab9fa80b}client_secret=d77469e6a7c8ae7486e9821fc118296a}scope=users:read,content:read,completions:read,required_learning:read,pathways:read,completions:read,search_terms:read,views:read,user_skills:read,skill:read,todays_learning:read,certificates:read}project_id=genentech-349217

gcloud functions deploy Creators --region=us-west1 --trigger-event providers/cloud.pubsub/eventTypes/topic.publish --trigger-resource WeeklySync --runtime=nodejs16 --source=./Creators/ --entry-point sync --timeout=540s --set-env-vars=^}^client_id=3088ab0aab9fa80b}client_secret=d77469e6a7c8ae7486e9821fc118296a}scope=users:read,content:read,completions:read,required_learning:read,pathways:read,completions:read,search_terms:read,views:read,user_skills:read,skill:read,todays_learning:read,certificates:read}project_id=genentech-349217

gcloud functions deploy PathwayProgress --region=us-west1 --trigger-event providers/cloud.pubsub/eventTypes/topic.publish --trigger-resource WeeklySync --runtime=nodejs16 --source=./PathwayProgress/ --entry-point sync --timeout=540s --set-env-vars=^}^client_id=3088ab0aab9fa80b}client_secret=d77469e6a7c8ae7486e9821fc118296a}scope=users:read,content:read,completions:read,required_learning:read,pathways:read,completions:read,search_terms:read,views:read,user_skills:read,skill:read,todays_learning:read,certificates:read}project_id=genentech-349217

gcloud functions deploy SearchTerms --region=us-west1 --trigger-event providers/cloud.pubsub/eventTypes/topic.publish --trigger-resource DailySync --runtime=nodejs16 --source=./SearchTerms/ --entry-point sync --timeout=540s --set-env-vars=^}^client_id=3088ab0aab9fa80b}client_secret=d77469e6a7c8ae7486e9821fc118296a}scope=users:read,content:read,completions:read,required_learning:read,pathways:read,completions:read,search_terms:read,views:read,user_skills:read,skill:read,todays_learning:read,certificates:read}project_id=genentech-349217

gcloud functions deploy Skills --region=us-west1 --trigger-event providers/cloud.pubsub/eventTypes/topic.publish --trigger-resource WeeklySync --runtime=nodejs16 --source=./Skills/ --entry-point sync --timeout=540s --set-env-vars=^}^client_id=3088ab0aab9fa80b}client_secret=d77469e6a7c8ae7486e9821fc118296a}scope=users:read,content:read,completions:read,required_learning:read,pathways:read,completions:read,search_terms:read,views:read,user_skills:read,skill:read,todays_learning:read,certificates:read}project_id=genentech-349217

gcloud functions deploy Users --region=us-west1 --trigger-event providers/cloud.pubsub/eventTypes/topic.publish --trigger-resource WeeklySync --runtime=nodejs16 --source=./Users/ --entry-point sync --timeout=540s --set-env-vars=^}^client_id=3088ab0aab9fa80b}client_secret=d77469e6a7c8ae7486e9821fc118296a}scope=users:read,content:read,completions:read,required_learning:read,pathways:read,completions:read,search_terms:read,views:read,user_skills:read,skill:read,todays_learning:read,certificates:read}project_id=genentech-349217

gcloud functions deploy Views --region=us-west1 --trigger-event providers/cloud.pubsub/eventTypes/topic.publish --trigger-resource DailySync --runtime=nodejs16 --source=./Views/ --entry-point sync --timeout=540s --set-env-vars=^}^client_id=3088ab0aab9fa80b}client_secret=d77469e6a7c8ae7486e9821fc118296a}scope=users:read,content:read,completions:read,required_learning:read,pathways:read,completions:read,search_terms:read,views:read,user_skills:read,skill:read,todays_learning:read,certificates:read}project_id=genentech-349217