name: Applying commands for role binding

on:
#   push:
#     branches: [ main ]
  pull_request:
    branches: 
      - main
    types: [closed]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}}  # project id here
  GKE_CLUSTER: cluster1 # cluster name here
  GKE_ZONE: us-central1-c # cluster zone here

jobs:
  rolebinding:
    name: Applying commands for role binding
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Google Cloud CLI
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        service_account_key: ${{secrets.GKE_SA_KEY}}
        project_id: ${{secrets.GKE_PROJECT}}
    - name: Get GKE Credentials
      run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
    - name: giving permission to script
      run: chmod 777 script.sh
    - name: applying command
      run: ./script.sh
